### ISSUE TITLE
Facing Crash on implementation of Silent bug report.

### ISSUE THREAD

**Issue by Yamini0** [GleapSDK/ReactNative-SDK#10]
Hey, I'm facing this bug while implementing SilentCrashReport in one of my Expo CLI. I had taken reference from https://docs.gleap.io/reactnative/silent-bug-reports/ and using like below.

`Gleap.sendSilentCrashReport('Silent Crash', 'HIGH', {
        customData: true,
        metaData: true,
        attachments: true,
        consoleLog: true,
        networkLogs: true,
        customEventLog: true,
        screenshot: true,
        replays: true,
      });`

Dependency Info:
Expo : 47.0.6
react-native-gleapsdk : 8.4.3

It will really helpful if someone can help me out to resolve this bug.
Thanks in advance.😇

![Simulator Screen Shot - iPhone 14 Pro - 2023-01-13 at 17 52 54](https://user-images.githubusercontent.com/77135583/212320091-5f87eeec-1d5b-4ed1-98ff-1b1b6ebb8371.png)

**Comment by boehlerlukas** [comment]
Hey @Yamini0 ,

thanks for reporting this issue. We were just looking into this and it turned out, our docs are not correct. There are two methods available:

`sendSilentCrashReport(
    description: string,
    severity: 'LOW' | 'MEDIUM' | 'HIGH'
  ): void;`

`sendSilentCrashReportWithExcludeData(
    description: string,
    severity: 'LOW' | 'MEDIUM' | 'HIGH',
    excludeData: {
      customData?: Boolean;
      metaData?: Boolean;
      attachments?: Boolean;
      consoleLog?: Boolean;
      networkLogs?: Boolean;
      customEventLog?: Boolean;
      screenshot?: Boolean;
      replays?: Boolean;
    }
  ): void;`

The second one needs to be used, if you want to also pass the excludeData. RN doesn't allow method overloading for plugins, which is why we needed to split the methods :)
